### ISSUE TITLE
Handle 503 errors

### ISSUE THREAD

**Issue by romanzenka** [Azure/AzureGraph#15]
When using the APIs, I am frequently running into 503s when I overwhelm the servers. In that case, there should be a Retry-After header asking me to delay and try again.

Can the library handle these errors automatically? Ideally there is a maximum delay one is willing to wait, so if service is down for longer than that, you get an error anyway.

**Comment by hongooi73** [comment]
Can you provide more context? It would be good to be able to handle 503 errors when they're part of the same overall request, eg when retrieving paged results. I think independent requests would have to be a matter for the user though.

**Comment by hongooi73** [comment]
Ok, I thought you were referring to [429 errors](https://docs.microsoft.com/en-us/graph/throttling?context=graph%2Fapi%2Fbeta&view=graph-rest-beta), which is what you get when you send too many requests. 503 is a generic "service unavailable" error which means that the server is having problems of its own. In this case, the best that you can do is try again later.

**Comment by hongooi73** [comment]
But see #17
