### ISSUE TITLE
Get user by email address

### ISSUE THREAD

**Issue by eitsupi** [Azure/AzureGraph#19]
Thank you for providing an easy-to-use library.
I wanted to get the user information from the user's email address, so I ran the code like this.

```R
library(AzureGraph)
gr <- create_graph_login()
usr <- gr$get_user("user_name@companyname.com")
```

However, it seems that only `userPrincipalName` can be used as an argument in `gr$get_user()` at the moment, and I couldn't get the user infomation with the user's email address.

Is there any other way to get user information from the email address?

**Comment by hongooi73** [comment]
Hi, thank for using the package.

You can list the users, with a filter on the `mail` property. There isn't a built-in method for this, but you can try calling the REST endpoint directly:

```r
val <- gr$call_graph_endpoint("users", options=list(`$filter`="mail eq 'user_name@company.com'")$value
```

This should be a list of length 1, which you can then use to initialise a user object.

```r
az_user$new(gr$token, gr$tenant, val[[1]])
```

I'll see about building this functionality into the next version.

**Comment by eitsupi** [comment]
> ```r
> val <- gr$call_graph_endpoint("users", options=list(`$filter`="mail eq 'user_name@company.com'"))$value
> ```

Thanks a lot ! That works for me well.

When I wanted to use the Azure Graph API, I was very fortunate to have such a great package in R and get an immediate answer.
