### ISSUE TITLE
Response using call_graph_url() is different from Graph Explorer

### ISSUE THREAD

**Issue by anapaularg** [Azure/AzureGraph#2]
Hi, I'm trying to use Graph API to read One Drive Excel values, for that I'm using the `AzureGraph` library. 

For this example, I'm trying to GET all the items in my drive.

Using the Graph Explorer I get a valid response, where the field "value" is not empty, and I can see my excel files.

![image](https://user-images.githubusercontent.com/10159306/67054397-08232a00-f10a-11e9-893d-50f251d39cb1.png)

However in R: 

`login <- create_graph_login(tenant = "3e0289c2-e351-4c79-998b-8167c83a06d3", auth_type = "resource_owner", username = "anapaula@brein.pe", password = "mypassword")

call_graph_endpoint(login$token, operation = "me/drive/root/children")`

This works and I get a 200 response, but the "value" filed is empty. 

![image](https://user-images.githubusercontent.com/10159306/67054464-43255d80-f10a-11e9-9c2a-7b1cceec6e1f.png)

I don't know what is the difference or what I may be doing wrong.

**Comment by Hong-Revo** [comment]
AzureGraph uses the beta API by default, not 1.0; this is because only the beta lets you work with apps and service principals. See if changing the API fixes it:

    call_graph_endpoint(token, operation, api_version="1.0")

**Comment by Hong-Revo** [comment]
Ok, it's not due to the endpoint. It's probably because the default token scope doesn't include the necessary permissions to access OneDrive. You can check this with

```r
AzureAuth::decode_jwt(login$token)$payload
```

and see if the `$scp` field includes anything like "Files.Read" or "Files.ReadWrite". To get around this you'll have to register your own app and give it the necessary permissions; the default app used by AzureGraph is meant for working with Azure, not Office so won't have the permissions required.

**Comment by anapaularg** [comment]
Ok, so I need the "Files.Read.All" permissions and I can see that I don't have them: 

![image](https://user-images.githubusercontent.com/10159306/67060653-61e41e00-f123-11e9-83f2-fc214a200825.png)

Then I went to the Azure Portal, registered and app and add this permissions (it's private cloud and I 'm not an admin but the permission here says that I don't need admin permissions)
![image](https://user-images.githubusercontent.com/10159306/67136387-1b59f680-f1eb-11e9-895e-6a4e9353d2ec.png)

Also I add this so I could use resource_owner

![image](https://user-images.githubusercontent.com/10159306/67136403-63791900-f1eb-11e9-89f7-d093f2e6a14d.png)

However, I get the following error: 

`scopes <- paste0("https://graph.microsoft.com/",c("User.Read", "Files.Read"))

tok <- AzureAuth::get_azure_token(resource = c(scopes,"offline_access"),
                                  tenant = "3e0289c2-e351-4c79-998b-8167c83a06d3",
                                  app = "2da13551-b7e2-4ad5-8430-87d52b2b60c6",
                                  version=2,
                                  auth_type = "resource_owner",
                                  username = "<my_email>",
                                  password = "<my_password>")

call_graph_endpoint(tok, "me/drive/root/children")
`
![image](https://user-images.githubusercontent.com/10159306/67136384-0bdaad80-f1eb-11e9-846e-644818e6bcdc.png)

What's is the configuration or auth_type required so I can get this running? Also this will be a an automated process to run every day, the idea is to read files from excel online (excel in one drive).

**Comment by Hong-Revo** [comment]
I think you still need to get your admin to approve the permissions. The portal is kinda badly designed.

The alternative is to use the app ID that OneDrive itself uses. I'll see if i can track that down, or you can try asking on StackOverflow.

**Comment by Hong-Revo** [comment]
So there is an app that OneDrive uses, but it requires a client secret. I think the only way is to create your own app.
