### ISSUE TITLE
Access denied when trying to send email

### ISSUE THREAD

**Issue by pieterjanvc** [Azure/AzureGraph#35]
Hello,

I'm trying to use your package to send emails from my outlook account. I have a created an app on Azure and given it the correct permission (at least I hope I did: send.mail). I now have the following code 

```r
library(AzureGraph)

gr <- get_graph_login()
myApp = gr$get_app("<token not shown>")

bodyJson = list(message = list(
  subject = "Hello from R",
  body=list(
    content="Hello from R",
    contentType="text"
  ),
  toRecipients=list(list(emailAddress = list(address = "someone@example.com")))
), saveToSentItems = "false")

req <- graph_request$new("me/sendMail",
                         body=bodyJson,
                         http_verb="POST"
)

call_batch_endpoint(myApp$token, list(req), api_version="v1.0")
```
However, when I run this I get the following error
```
Error: Graph batch job encountered errors on requests 1
Messages:
Access is denied. Check credentials and try again.
```

Do you have any feedback on what I should do next?

Kind regards

**Comment by hongooi73** [comment]
To send mail, I recommend using my [Microsoft365R](https://github.com/Azure/Microsoft365R) package. It has an interface to Outlook, as well as Sharepoint, OneDrive and Teams.

**Comment by hongooi73** [comment]
You should also be able to reuse your app ID with Microsoft365R. You won't be able to use the other MS365 services, but Outlook should work fine, assuming you've set the permissions correctly.
