### ISSUE TITLE
Add SharePoint File Upload

### ISSUE THREAD

**Issue by bigbird023** [Azure/AzureGraph#9]
Want to be able to generate a report in R and publish to a sharepoint site

**Comment by bigbird023** [comment]
rough but working codebase

https://github.com/PennState/AzureGraph/tree/feature/UpDownload

**Comment by hongooi73** [comment]
This is now available in [Microsoft365R](https://github.com/Azure/Microsoft365R), which should be heading to CRAN before too long.

**Comment by bigbird023** [comment]
awesome!

**Comment by hongooi73** [comment]
Microsoft365R is now on CRAN.
